### ISSUE TITLE
Using Cygwin without scoop?

### ISSUE THREAD

**Issue by apppppppple** [Adriankhl/wsl2-xwin-audio#2]
I installed Cygwin using the setup-x86_64.exe from [here](https://cygwin.com/install.html). It seems to work fine but I can't find a cygwin.exe anywhere. There is a Cygwin.bat but it just runs the bash.exe that came bundled with cygwin. The bash kind of works but there aren't any of the commands that seem like they're supposed to be there to use for this. Do I need to reinstall with scoop to get it to work?

**Comment by Adriankhl** [comment]
You can try to do something like this `./bash.exe --login -i -c "XWin :0 -listen tcp -retro -lesspointer -multiwindow -clipboard -ac -nowgl"`

The argument after `-c` is the command that should be executed after entering the bash shell

**Comment by apppppppple** [comment]
oh ok thanks! sorry to bother you
